-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY


SELECT HISTORY_ID,
       CAR_ID,
       START_DATE,
       END_DATE,
       COUNT(HISTORY_ID) OVER (PARTITION BY CAR_ID) AS cnt
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
  AND START_DATE <= '2022-10-31'


-- 날짜 적용 및 카운트 차들.
SELECT HISTORY_ID,
       CAR_ID,
       START_DATE,
       END_DATE,
       COUNT(HISTORY_ID) OVER (PARTITION BY CAR_ID) AS cnt
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
  AND START_DATE <= '2022-10-31'



SELECT MONTH, CAR_ID, cnt AS RECORDS
FROM (
    SELECT CAR_ID, MONTH (START_DATE) MONTH, COUNT (HISTORY_ID) OVER (PARTITION BY CAR_ID) AS cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    ) AS cntTable
WHERE cnt >= 5
ORDER BY MONTH ASC, CAR_ID DESC

SELECT MONTH, CAR_ID, cnt AS RECORDS
FROM (
    SELECT CAR_ID, MONTH (START_DATE) MONTH, COUNT (HISTORY_ID) OVER (PARTITION BY CAR_ID) AS cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY MONTH (START_DATE)
    ) AS cntTable
WHERE cnt >= 5
ORDER BY MONTH ASC, CAR_ID DESC;

--

SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
  AND START_DATE <= '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(HISTORY_ID) >= 5

SELECT MONTH (START_DATE) AS MONTH, CAR_ID, COUNT (HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
  AND START_DATE <= '2022-10-31'
  AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
  AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT (HISTORY_ID) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH (START_DATE) ASC, CAR_ID DESC;
