-- Gemini

SELECT PRODUCT_ID, SCORE, CONTENT, CREATED_AT
FROM PRODUCT_REVIEWS WEHRE (
                            SELECT ROW_NUMBER(OVER PRODUCT_ID ORDER BY SCORE DESC) AS row,
                            FROM PRODUCT_REVIEWS
    )


SELECT PRODUCT_ID,
       SCORE,
       CONTENT,
       CREATED_AT
       (
           SELECT PRODUCT_ID, SCORE, CONTENT, CREATED_AT, ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY SCORE DESC, CREATED_AT DESC) AS rnk
FROM PRODUCT_REVIEWS
       ) WHERE rnk = 1
ORDER BY PRODUCT_ID ASC;