-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT CAR_ID, COUNT(CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
  AND END_DATE <= '2022-10-31'
GROUP BY CAR_ID
ORDER BY CAR_ID ASC;



SELECT MONTH, CAR_ID, RECORDS
FROM (SELECT CAR_ID, COUNT (CAR_ID) AS RECORDS, MONTH (START_DATE) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID) AS counttable
WHERE RECORDS >= 5 AND RECORDS <> 0
ORDER BY MONTH ASC, CAR_ID DESC;


SELECT MONTH, CAR_ID, cnt AS RECORDS
FROM
    (SELECT CAR_ID, MONTH(START_DATE) AS MONTH, COUNT(CAR_ID) OVER (PARTITION BY CAR_ID) AS cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31') As CountTable
WHERE cnt >= 5
ORDER BY MONTH ASC, CAR_ID DESC;




